export interface ModuleSetupOptions {
  extractorType: string;
  dbSettingKey: string;
  autoInjectTenantId: boolean;
  sharedModels: string[];
}

export function generateModuleSetup(options: ModuleSetupOptions): string {
  const lines: string[] = [
    '// Generated by @nestarc/tenancy CLI',
    '// Add to your AppModule imports array.',
    '',
    "import { TenancyModule } from '@nestarc/tenancy';",
    '',
    '// In your @Module({ imports: [...] })',
    'TenancyModule.forRoot({',
  ];

  switch (options.extractorType) {
    case 'Subdomain (tenant1.app.com)':
      lines.push('  tenantExtractor: new SubdomainTenantExtractor(),');
      break;
    case 'JWT Claim':
      lines.push(
        "  tenantExtractor: new JwtClaimTenantExtractor({ claimKey: 'tenant_id' }),",
      );
      break;
    case 'Path Parameter':
      lines.push(
        "  tenantExtractor: new PathTenantExtractor({ pattern: '/api/tenants/:tenantId' }),",
      );
      break;
    default:
      lines.push("  tenantExtractor: 'X-Tenant-Id',");
  }

  if (options.dbSettingKey !== 'app.current_tenant') {
    lines.push(`  dbSettingKey: '${options.dbSettingKey}',`);
  }

  lines.push('})');

  if (options.autoInjectTenantId || options.sharedModels.length > 0) {
    lines.push('');
    lines.push('// Prisma extension options:');
    lines.push('createPrismaTenancyExtension(tenancyService, {');
    if (options.autoInjectTenantId) {
      lines.push('  autoInjectTenantId: true,');
    }
    if (options.sharedModels.length > 0) {
      lines.push(
        `  sharedModels: [${options.sharedModels.map((m) => `'${m}'`).join(', ')}],`,
      );
    }
    lines.push('})');
  }

  return lines.join('\n');
}
