export interface ModuleSetupOptions {
  extractorType: string;
  dbSettingKey: string;
  autoInjectTenantId: boolean;
  sharedModels: string[];
}

export function generateModuleSetup(options: ModuleSetupOptions): string {
  // Determine which extractor class (if any) needs to be imported
  const extractorImportMap: Record<string, string> = {
    'Subdomain (tenant1.app.com)': 'SubdomainTenantExtractor',
    'JWT Claim': 'JwtClaimTenantExtractor',
    'Path Parameter': 'PathTenantExtractor',
  };
  const extractorClass = extractorImportMap[options.extractorType];

  const usePrismaExtension =
    options.autoInjectTenantId || options.sharedModels.length > 0;

  const lines: string[] = [
    '// Generated by @nestarc/tenancy CLI',
    '// Add to your AppModule imports array.',
    '',
  ];

  // Build the import from @nestarc/tenancy
  const namedImports: string[] = ['TenancyModule'];
  if (extractorClass) {
    namedImports.push(extractorClass);
  }
  if (usePrismaExtension) {
    namedImports.push('createPrismaTenancyExtension');
  }
  lines.push(`import { ${namedImports.join(', ')} } from '@nestarc/tenancy';`);
  lines.push('');

  lines.push('// In your @Module({ imports: [...] })', 'TenancyModule.forRoot({');

  switch (options.extractorType) {
    case 'Subdomain (tenant1.app.com)':
      lines.push('  tenantExtractor: new SubdomainTenantExtractor(),');
      break;
    case 'JWT Claim':
      lines.push(
        "  tenantExtractor: new JwtClaimTenantExtractor({ claimKey: 'tenant_id' }),",
      );
      break;
    case 'Path Parameter':
      lines.push(
        "  tenantExtractor: new PathTenantExtractor({ pattern: '/api/tenants/:tenantId' }),",
      );
      break;
    case 'Composite':
      lines.push('  tenantExtractor: /* configure your CompositeExtractor here */,');
      break;
    default:
      lines.push("  tenantExtractor: 'X-Tenant-Id',");
  }

  if (options.dbSettingKey !== 'app.current_tenant') {
    lines.push(`  dbSettingKey: '${options.dbSettingKey}',`);
  }

  lines.push('})');

  if (usePrismaExtension) {
    lines.push('');
    lines.push('// Prisma extension options:');
    lines.push('createPrismaTenancyExtension(tenancyService, {');
    if (options.autoInjectTenantId) {
      lines.push('  autoInjectTenantId: true,');
    }
    if (options.sharedModels.length > 0) {
      lines.push(
        `  sharedModels: [${options.sharedModels.map((m) => `'${m}'`).join(', ')}],`,
      );
    }
    lines.push('})');
  }

  return lines.join('\n');
}
