import { ParsedModel } from '../prisma-schema-parser';
import {
  assertValidPostgresIdentifier,
  assertValidPostgresSettingKey,
  quoteSqlIdentifier,
  quoteSqlLiteral,
} from '../../postgres-safety';
import { generateRelationNames } from '../generated-name';

export interface SetupSqlOptions {
  models: ParsedModel[];
  dbSettingKey: string;
  sharedModels: string[];
  tenantIdField: string;
}

function qualifiedTableName(model: ParsedModel): string {
  if (model.schemaName) {
    return `${quoteSqlIdentifier(model.schemaName)}.${quoteSqlIdentifier(model.tableName)}`;
  }
  return `${quoteSqlIdentifier('public')}.${quoteSqlIdentifier(model.tableName)}`;
}

function sqlCommentText(value: string): string {
  return value.replace(/\r/g, '\\r').replace(/\n/g, '\\n');
}

function commentedSql(statement: string): string {
  return statement
    .split(/\r\n|\r|\n/)
    .map((line) => `-- ${line}`)
    .join('\n');
}

function unusedDollarQuoteTag(value: string, base: string): string {
  for (let suffix = 0; ; suffix++) {
    const tag = suffix === 0 ? `$${base}$` : `$${base}_${suffix}$`;
    if (!value.includes(tag)) return tag;
  }
}

function dollarQuotedSqlLiteral(value: string): string {
  const tag = unusedDollarQuoteTag(value, 'tenancy_identifier');
  return `${tag}${value}${tag}`;
}

function createPolicyIfMissing(
  policyName: string,
  schemaName: string,
  relationName: string,
  statement: string[],
): string[] {
  const body = [
    'BEGIN',
    '  IF NOT EXISTS (',
    '    SELECT 1',
    '    FROM pg_catalog.pg_policy AS p',
    '    JOIN pg_catalog.pg_class AS c ON c.oid = p.polrelid',
    '    JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace',
    `    WHERE n.nspname = ${dollarQuotedSqlLiteral(schemaName)}`,
    `      AND c.relname = ${dollarQuotedSqlLiteral(relationName)}`,
    `      AND p.polname = ${quoteSqlLiteral(policyName.toLowerCase())}::pg_catalog.name`,
    '  ) THEN',
    ...statement.map((line) => `    ${line}`),
    '  END IF;',
    'END',
  ];
  const tag = unusedDollarQuoteTag(body.join('\n'), 'tenancy_policy');
  return [`DO ${tag}`, ...body, `${tag};`];
}

function validateOptions(options: SetupSqlOptions): void {
  assertValidPostgresSettingKey(options.dbSettingKey);
  assertValidPostgresIdentifier(
    options.tenantIdField,
    'Tenant column PostgreSQL identifier',
  );

  for (const model of options.models) {
    if (typeof model.modelName !== 'string' || model.modelName.includes('\0')) {
      throw new Error('Prisma model name must be a string without NUL bytes.');
    }
    assertValidPostgresIdentifier(
      model.tableName,
      'Table PostgreSQL identifier',
    );
    if (model.schemaName !== undefined) {
      assertValidPostgresIdentifier(
        model.schemaName,
        'Schema PostgreSQL identifier',
      );
    }
  }
}

export function generateSetupSql(options: SetupSqlOptions): string {
  validateOptions(options);
  const { models, dbSettingKey, sharedModels, tenantIdField } = options;
  const sharedSet = new Set(sharedModels);
  const tenantColumn = quoteSqlIdentifier(tenantIdField);
  const settingKeyLiteral = quoteSqlLiteral(dbSettingKey);
  const generatedNames = models
    .filter((model) => !sharedSet.has(model.modelName))
    .map((model) => generateRelationNames({
      schemaName: model.schemaName,
      tableName: model.tableName,
      tenantIdField,
    }));
  let generatedNameIndex = 0;

  // Collect unique schemas for GRANT USAGE statements
  const schemas = new Set<string>(['public']);
  for (const model of models) {
    schemas.add(model.schemaName ?? 'public');
  }

  const lines: string[] = [
    '-- Generated by @nestarc/tenancy CLI',
    '-- BEGIN GENERATED TENANCY SQL',
    '-- Review and customize before running against your database.',
    `-- IMPORTANT: This script assumes all non-shared models have a '${sqlCommentText(tenantIdField)}' column.`,
    '-- Remove or modify policies for models that don\'t use tenant isolation.',
    '-- Run this as a standalone script; the generated block uses one explicit transaction.',
    '-- Use a fail-fast client; with psql, use -X -v ON_ERROR_STOP=1 and not ON_ERROR_ROLLBACK=on.',
    '-- On error, issue ROLLBACK or close the session before running any other statement.',
    '-- Existing policies with generated names are preserved during reapply so drift is not overwritten.',
    '-- Existing short names stay unchanged for canonical lowercase ASCII inputs except legacy explicit public_ names.',
    '-- Lossy, case-folded, or overlong names use a stable hash suffix; explicit and implicit public schemas share one identity.',
    '-- Review applied policy drift with `tenancy doctor`.',
    '-- For atomic replacement, use a temporary reviewed copy with an explicit DROP POLICY after BEGIN.',
    '',
    'BEGIN;',
    '',
    '-- Create a non-superuser role for the application',
    "-- Set a strong password before using this role in production:",
    "-- ALTER ROLE app_user WITH PASSWORD 'replace-with-strong-password';",
    'DO $$',
    'BEGIN',
    "  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN",
    '    CREATE ROLE app_user LOGIN;',
    '  END IF;',
    'END',
    '$$;',
    '',
    '-- GRANT CONNECT ON DATABASE your_database TO app_user;',
  ];

  // Grant schema usage for each unique schema
  for (const schema of schemas) {
    lines.push(`GRANT USAGE ON SCHEMA ${quoteSqlIdentifier(schema)} TO app_user;`);
  }
  lines.push('');

  for (const model of models) {
    const tableName = qualifiedTableName(model);
    const schemaForSeq = model.schemaName ?? 'public';

    if (sharedSet.has(model.modelName)) {
      lines.push(`-- ${sqlCommentText(model.modelName)} (shared model)`);
      lines.push(
        `GRANT SELECT, INSERT, UPDATE, DELETE ON ${tableName} TO app_user;`,
      );
      lines.push('-- Also grant sequence permissions if using SERIAL/autoincrement columns:');
      lines.push(commentedSql(
        `GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ${quoteSqlIdentifier(schemaForSeq)} TO app_user;`,
      ));
      lines.push('');
      continue;
    }

    const names = generatedNames[generatedNameIndex++];
    const isolationPolicy = names.isolationPolicy;
    const insertPolicy = names.insertPolicy;
    lines.push(`-- ${sqlCommentText(model.modelName)}`);
    lines.push(`ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;`);
    lines.push(`ALTER TABLE ${tableName} FORCE ROW LEVEL SECURITY;`);
    lines.push(
      `CREATE INDEX IF NOT EXISTS ${names.index} ON ${tableName} (${tenantColumn});`,
    );
    lines.push(...createPolicyIfMissing(
      isolationPolicy,
      model.schemaName ?? 'public',
      model.tableName,
      [
        `CREATE POLICY ${isolationPolicy} ON ${tableName}`,
        `  USING (${tenantColumn} = current_setting(${settingKeyLiteral}, true)::text);`,
      ],
    ));
    lines.push(...createPolicyIfMissing(
      insertPolicy,
      model.schemaName ?? 'public',
      model.tableName,
      [
        `CREATE POLICY ${insertPolicy} ON ${tableName}`,
        `  FOR INSERT WITH CHECK (${tenantColumn} = current_setting(${settingKeyLiteral}, true)::text);`,
      ],
    ));
    lines.push(
      `GRANT SELECT, INSERT, UPDATE, DELETE ON ${tableName} TO app_user;`,
    );
    lines.push('-- Also grant sequence permissions if using SERIAL/autoincrement columns:');
    lines.push(commentedSql(
      `GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ${quoteSqlIdentifier(schemaForSeq)} TO app_user;`,
    ));
    lines.push('');
  }

  // General sequence grant for each schema
  lines.push('-- Grant sequence permissions for all sequences:');
  for (const schema of schemas) {
    lines.push(`GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ${quoteSqlIdentifier(schema)} TO app_user;`);
  }
  lines.push('COMMIT;');
  lines.push('-- END GENERATED TENANCY SQL');

  return lines.join('\n');
}
