import { ParsedModel } from '../prisma-schema-parser';

export interface SetupSqlOptions {
  models: ParsedModel[];
  dbSettingKey: string;
  sharedModels: string[];
  tenantIdField: string;
}

export function generateSetupSql(options: SetupSqlOptions): string {
  const { models, dbSettingKey, sharedModels, tenantIdField } = options;
  const sharedSet = new Set(sharedModels);

  const lines: string[] = [
    '-- Generated by @nestarc/tenancy CLI',
    '-- Review and customize before running against your database.',
    '',
    '-- Create a non-superuser role for the application',
    'DO $$',
    'BEGIN',
    "  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN",
    "    CREATE ROLE app_user LOGIN PASSWORD 'changeme';",
    '  END IF;',
    'END',
    '$$;',
    '',
    'GRANT USAGE ON SCHEMA public TO app_user;',
    '',
  ];

  for (const model of models) {
    if (sharedSet.has(model.modelName)) {
      lines.push(`-- ${model.modelName} (shared model)`);
      lines.push(
        `GRANT SELECT, INSERT, UPDATE, DELETE ON "${model.tableName}" TO app_user;`,
      );
      lines.push('');
      continue;
    }

    lines.push(`-- ${model.modelName}`);
    lines.push(`ALTER TABLE "${model.tableName}" ENABLE ROW LEVEL SECURITY;`);
    lines.push(
      `CREATE POLICY tenant_isolation_${model.tableName} ON "${model.tableName}"`,
    );
    lines.push(
      `  USING (${tenantIdField} = current_setting('${dbSettingKey}', true)::text);`,
    );
    lines.push(
      `CREATE POLICY tenant_insert_${model.tableName} ON "${model.tableName}"`,
    );
    lines.push(
      `  FOR INSERT WITH CHECK (${tenantIdField} = current_setting('${dbSettingKey}', true)::text);`,
    );
    lines.push(
      `GRANT SELECT, INSERT, UPDATE, DELETE ON "${model.tableName}" TO app_user;`,
    );
    lines.push('');
  }

  return lines.join('\n');
}
