import * as fs from 'fs';
import * as path from 'path';
import { parseModels, ParsedModel } from './prisma-schema-parser';
import {
  isValidPostgresSettingKey,
  quoteSqlIdentifier,
  quoteSqlLiteral,
} from '../postgres-safety';
import { DEFAULT_DB_SETTING_KEY } from '../tenancy.constants';
import { generateRelationNames } from './generated-name';

interface CheckOptions {
  cwd?: string;
  dbSettingKey?: string;
  tenantIdField?: string;
}

const GENERATED_START = '-- BEGIN GENERATED TENANCY SQL';
const GENERATED_END = '-- END GENERATED TENANCY SQL';
const GENERATED_HEADER = 'Generated by @nestarc/tenancy CLI';

export interface CheckResult {
  inSync: boolean;
  missingPolicies: string[];
  extraPolicies: string[];
  warnings: string[];
}

function qualifiedName(model: ParsedModel): string {
  return model.schemaName
    ? `${quoteSqlIdentifier(model.schemaName)}.${quoteSqlIdentifier(model.tableName)}`
    : quoteSqlIdentifier(model.tableName);
}

function canonicalTableName(tableName: string): string {
  let insideIdentifier = false;
  for (let index = 0; index < tableName.length; index++) {
    if (tableName[index] === '"') {
      if (insideIdentifier && tableName[index + 1] === '"') {
        index++;
      } else {
        insideIdentifier = !insideIdentifier;
      }
    } else if (!insideIdentifier && tableName[index] === '.') {
      return tableName;
    }
  }
  return `${quoteSqlIdentifier('public')}.${tableName}`;
}

function extractGeneratedSqlSection(
  sqlContent: string,
  lineComments: SqlLineComment[],
): string {
  const startMarker = GENERATED_START.slice(2).trim();
  const endMarker = GENERATED_END.slice(2).trim();
  const start = lineComments.find(
    (comment) => comment.text.trim() === startMarker,
  );
  const end = lineComments.find(
    (comment) =>
      comment.start > (start?.start ?? -1) &&
      comment.text.trim() === endMarker,
  );

  if (!start || !end) {
    return sqlContent;
  }

  return sqlContent.slice(start.end, end.start);
}

interface SqlLineComment {
  text: string;
  start: number;
  end: number;
}

interface ScannedSql {
  code: string;
  lineComments: SqlLineComment[];
  statements: string[];
  stringLiterals: SqlStringLiteral[];
  valid: boolean;
}

interface SqlStringLiteral {
  standard: boolean;
  dollarQuoted: boolean;
  value: string;
}

const SQL_STRING_TOKEN_PREFIX = '\0TENANCY_SQL_STRING_';
const SQL_STRING_TOKEN_SUFFIX = '\0';

function sqlStringToken(index: number): string {
  return `${SQL_STRING_TOKEN_PREFIX}${index}${SQL_STRING_TOKEN_SUFFIX}`;
}

function sqlStringTokenIndex(value: string): number | undefined {
  if (
    !value.startsWith(SQL_STRING_TOKEN_PREFIX) ||
    !value.endsWith(SQL_STRING_TOKEN_SUFFIX)
  ) {
    return undefined;
  }
  const serializedIndex = value.slice(
    SQL_STRING_TOKEN_PREFIX.length,
    -SQL_STRING_TOKEN_SUFFIX.length,
  );
  return /^\d+$/.test(serializedIndex)
    ? Number(serializedIndex)
    : undefined;
}

function scanSql(sqlContent: string): ScannedSql {
  let code = '';
  let statementStart = 0;
  let blockCommentDepth = 0;
  let valid = !sqlContent.includes('\0');
  const lineComments: SqlLineComment[] = [];
  const statements: string[] = [];
  const stringLiterals: SqlStringLiteral[] = [];

  for (let index = 0; index < sqlContent.length; index++) {
    const character = sqlContent[index];
    const nextCharacter = sqlContent[index + 1];

    if (blockCommentDepth > 0) {
      if (character === '/' && nextCharacter === '*') {
        blockCommentDepth++;
        index++;
      } else if (character === '*' && nextCharacter === '/') {
        blockCommentDepth--;
        index++;
      } else if (character === '\n' || character === '\r') {
        code += character;
      }
      continue;
    }

    if (character === '-' && nextCharacter === '-') {
      const commentStart = index;
      let comment = '';
      index += 2;
      while (
        index < sqlContent.length &&
        sqlContent[index] !== '\n' &&
        sqlContent[index] !== '\r'
      ) {
        comment += sqlContent[index];
        index++;
      }
      lineComments.push({
        text: comment,
        start: commentStart,
        end: index,
      });
      index--;
      continue;
    }

    if (character === '/' && nextCharacter === '*') {
      blockCommentDepth = 1;
      code += ' ';
      index++;
      continue;
    }

    if (character === "'") {
      const prefix = sqlContent[index - 1];
      const beforePrefix = sqlContent[index - 2];
      const isEscapeString =
        (prefix === 'E' || prefix === 'e') &&
        (beforePrefix === undefined ||
          !/[A-Za-z0-9_$\u0080-\uFFFF]/u.test(beforePrefix));
      const beforeUnicodePrefix = sqlContent[index - 3];
      const isUnicodeString =
        prefix === '&' &&
        (beforePrefix === 'U' || beforePrefix === 'u') &&
        (beforeUnicodePrefix === undefined ||
          !/[A-Za-z0-9_$\u0080-\uFFFF]/u.test(beforeUnicodePrefix));
      if (isEscapeString) code = code.slice(0, -1);
      else if (isUnicodeString) code = code.slice(0, -2);
      let literal = '';
      let closed = false;
      for (let literalIndex = index + 1; literalIndex < sqlContent.length; literalIndex++) {
        const literalCharacter = sqlContent[literalIndex];
        if (
          isEscapeString &&
          literalCharacter === '\\' &&
          literalIndex + 1 < sqlContent.length
        ) {
          literal += sqlContent[literalIndex + 1];
          literalIndex++;
          continue;
        }
        if (literalCharacter === "'") {
          if (sqlContent[literalIndex + 1] === "'") {
            literal += "'";
            literalIndex++;
            continue;
          }
          index = literalIndex;
          closed = true;
          break;
        }
        literal += literalCharacter;
      }
      if (!closed) {
        valid = false;
        index = sqlContent.length;
        continue;
      }
      const literalIndex = stringLiterals.push({
        standard: !isEscapeString && !isUnicodeString,
        dollarQuoted: false,
        value: literal,
      }) - 1;
      code += sqlStringToken(literalIndex);
      continue;
    }

    if (character === '"') {
      code += character;
      let closed = false;
      for (let identifierIndex = index + 1; identifierIndex < sqlContent.length; identifierIndex++) {
        const identifierCharacter = sqlContent[identifierIndex];
        code += identifierCharacter;
        if (identifierCharacter === '"') {
          if (sqlContent[identifierIndex + 1] === '"') {
            code += sqlContent[identifierIndex + 1];
            identifierIndex++;
            continue;
          }
          index = identifierIndex;
          closed = true;
          break;
        }
      }
      if (!closed) {
        valid = false;
        index = sqlContent.length;
      }
      continue;
    }

    if (character === '$') {
      const previousCharacter = sqlContent[index - 1];
      const hasTokenBoundary =
        previousCharacter === undefined ||
        !/[A-Za-z0-9_$\u0080-\uFFFF]/u.test(previousCharacter);
      const dollarTag = hasTokenBoundary
        ? /^\$(?:[A-Za-z_\u0080-\uFFFF][A-Za-z0-9_\u0080-\uFFFF]*)?\$/u
          .exec(sqlContent.slice(index))?.[0]
        : undefined;
      if (dollarTag) {
        const bodyStart = index + dollarTag.length;
        const bodyEnd = sqlContent.indexOf(dollarTag, bodyStart);
        if (bodyEnd === -1) {
          valid = false;
          index = sqlContent.length;
          continue;
        }
        const literalIndex = stringLiterals.push({
          standard: false,
          dollarQuoted: true,
          value: sqlContent.slice(bodyStart, bodyEnd),
        }) - 1;
        code += sqlStringToken(literalIndex);
        index = bodyEnd + dollarTag.length - 1;
        continue;
      }
    }

    if (character === ';') {
      code += character;
      statements.push(code.slice(statementStart));
      statementStart = code.length;
      continue;
    }

    code += character;
  }

  const trailingStatement = code.slice(statementStart);
  if (trailingStatement.trim().length > 0) {
    statements.push(trailingStatement);
  }

  if (blockCommentDepth > 0) valid = false;

  return { code, lineComments, statements, stringLiterals, valid };
}

function maskSqlQuotedIdentifiers(sqlCode: string): string {
  let masked = '';

  for (let index = 0; index < sqlCode.length; index++) {
    const character = sqlCode[index];
    if (character !== '"') {
      masked += character;
      continue;
    }

    masked += ' ';
    for (index += 1; index < sqlCode.length; index++) {
      const identifierCharacter = sqlCode[index];
      masked += identifierCharacter === '\n' || identifierCharacter === '\r'
        ? identifierCharacter
        : ' ';
      if (identifierCharacter !== '"') continue;
      if (sqlCode[index + 1] === '"') {
        masked += ' ';
        index++;
        continue;
      }
      break;
    }
  }

  return masked;
}

function isSupportedGeneratedTopLevelStatement(statement: string): boolean {
  if (statement === 'BEGIN' || statement === 'COMMIT') return true;

  const quotedIdentifier = '"(?:[^"]|"")*"';
  const qualifiedTable = `${quotedIdentifier}\\.${quotedIdentifier}`;
  const stringToken =
    `${escapeRegExp(SQL_STRING_TOKEN_PREFIX)}\\d+${escapeRegExp(SQL_STRING_TOKEN_SUFFIX)}`;
  const supportedPatterns = [
    new RegExp(`^DO\\s+${stringToken}$`, 'i'),
    new RegExp(
      `^GRANT\\s+USAGE\\s+ON\\s+SCHEMA\\s+${quotedIdentifier}\\s+TO\\s+app_user$`,
      'i',
    ),
    new RegExp(
      `^ALTER\\s+TABLE\\s+${qualifiedTable}\\s+(?:ENABLE|FORCE)\\s+ROW\\s+LEVEL\\s+SECURITY$`,
      'i',
    ),
    new RegExp(
      `^CREATE\\s+INDEX\\s+IF\\s+NOT\\s+EXISTS\\s+[A-Za-z_][A-Za-z0-9_]*\\s+ON\\s+${qualifiedTable}\\s+\\(${quotedIdentifier}\\)$`,
      'i',
    ),
    new RegExp(
      `^GRANT\\s+SELECT\\s*,\\s*INSERT\\s*,\\s*UPDATE\\s*,\\s*DELETE\\s+ON\\s+${qualifiedTable}\\s+TO\\s+app_user$`,
      'i',
    ),
    new RegExp(
      `^GRANT\\s+USAGE\\s*,\\s*SELECT\\s+ON\\s+ALL\\s+SEQUENCES\\s+IN\\s+SCHEMA\\s+${quotedIdentifier}\\s+TO\\s+app_user$`,
      'i',
    ),
  ];
  return supportedPatterns.some((pattern) => pattern.test(statement));
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function stringLiteralForToken(
  scannedSql: ScannedSql,
  token: string,
): SqlStringLiteral | undefined {
  const index = sqlStringTokenIndex(token);
  return index === undefined ? undefined : scannedSql.stringLiterals[index];
}

function restoreStandardStringTokens(
  value: string,
  scannedSql: ScannedSql,
): string | undefined {
  const tokenPattern = new RegExp(
    `${escapeRegExp(SQL_STRING_TOKEN_PREFIX)}\\d+${escapeRegExp(SQL_STRING_TOKEN_SUFFIX)}`,
    'g',
  );
  let supported = true;
  const restored = value.replace(tokenPattern, (token) => {
    const literal = stringLiteralForToken(scannedSql, token);
    if (!literal?.standard) {
      supported = false;
      return token;
    }
    return quoteSqlLiteral(literal.value);
  });
  return supported ? restored : undefined;
}

interface GuardedPolicyInspection {
  statements: string[];
  unsupportedDo: boolean;
}

const GENERATED_ROLE_BLOCK_BODY = [
  'BEGIN',
  "  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN",
  '    CREATE ROLE app_user LOGIN;',
  '  END IF;',
  'END',
].join('\n');

function inspectGuardedPolicyStatements(
  scannedSql: ScannedSql,
): GuardedPolicyInspection {
  if (!scannedSql.valid) {
    return { statements: [], unsupportedDo: false };
  }

  const tokenPattern =
    `${escapeRegExp(SQL_STRING_TOKEN_PREFIX)}\\d+${escapeRegExp(SQL_STRING_TOKEN_SUFFIX)}`;
  const doPattern = new RegExp(`^DO\\s+(${tokenPattern})$`, 'i');
  const guardPattern = new RegExp(
    '^BEGIN\\s+IF\\s+NOT\\s+EXISTS\\s*\\(\\s*' +
      'SELECT\\s+1\\s+FROM\\s+pg_catalog\\.pg_policy\\s+AS\\s+p\\s+' +
      'JOIN\\s+pg_catalog\\.pg_class\\s+AS\\s+c\\s+ON\\s+c\\.oid\\s*=\\s*p\\.polrelid\\s+' +
      'JOIN\\s+pg_catalog\\.pg_namespace\\s+AS\\s+n\\s+ON\\s+n\\.oid\\s*=\\s*c\\.relnamespace\\s+' +
      `WHERE\\s+n\\.nspname\\s*=\\s*(${tokenPattern})\\s+` +
      `AND\\s+c\\.relname\\s*=\\s*(${tokenPattern})\\s+` +
      `AND\\s+p\\.polname\\s*=\\s*(${tokenPattern})\\s*::\\s*pg_catalog\\.name\\s*` +
      '\\)\\s+THEN\\s+(CREATE\\s+POLICY[\\s\\S]+)$',
    'i',
  );
  const quotedIdentifier = '"(?:[^"]|"")*"';
  const qualifiedTable = `${quotedIdentifier}(?:\\.${quotedIdentifier})?`;
  const createPattern = new RegExp(
    `^CREATE\\s+POLICY\\s+([A-Za-z_][A-Za-z0-9_]*)\\s+ON\\s+(${qualifiedTable})(?:\\s|$)`,
    'i',
  );
  const policies: string[] = [];
  let unsupportedDo = false;

  for (const statement of scannedSql.statements) {
    const topLevel = statement.replace(/;\s*$/, '').trim();
    if (!/^DO(?:\s|$)/i.test(topLevel)) continue;
    const doMatch = doPattern.exec(topLevel);
    if (!doMatch) {
      unsupportedDo = true;
      continue;
    }

    const body = stringLiteralForToken(scannedSql, doMatch[1]);
    if (!body?.dollarQuoted) {
      unsupportedDo = true;
      continue;
    }
    const normalizedBody = body.value.replace(/\r\n?/g, '\n').trim();
    if (normalizedBody === GENERATED_ROLE_BLOCK_BODY) continue;

    const bodyScan = scanSql(body.value);
    const bodyStatements = bodyScan.statements.map((candidate) =>
      candidate.replace(/;\s*$/, '').trim(),
    );
    if (
      !bodyScan.valid ||
      bodyScan.lineComments.length > 0 ||
      bodyStatements.length !== 3 ||
      bodyStatements[1] !== 'END IF' ||
      bodyStatements[2] !== 'END'
    ) {
      unsupportedDo = true;
      continue;
    }

    const guardMatch = guardPattern.exec(bodyStatements[0]);
    if (!guardMatch) {
      unsupportedDo = true;
      continue;
    }
    const guardedSchema = stringLiteralForToken(bodyScan, guardMatch[1]);
    const guardedTable = stringLiteralForToken(bodyScan, guardMatch[2]);
    const guardedPolicy = stringLiteralForToken(bodyScan, guardMatch[3]);
    const createStatement = restoreStandardStringTokens(
      guardMatch[4].trim(),
      bodyScan,
    );
    if (
      !guardedSchema?.dollarQuoted ||
      !guardedTable?.dollarQuoted ||
      !guardedPolicy?.standard ||
      !createStatement
    ) {
      unsupportedDo = true;
      continue;
    }

    const createMatch = createPattern.exec(createStatement);
    let expectedTableNames: string[];
    try {
      const quotedSchema = quoteSqlIdentifier(guardedSchema.value);
      const quotedTable = quoteSqlIdentifier(guardedTable.value);
      expectedTableNames = [`${quotedSchema}.${quotedTable}`];
    } catch {
      unsupportedDo = true;
      continue;
    }
    if (
      !createMatch ||
      !expectedTableNames.includes(createMatch[2]) ||
      guardedPolicy.value !== createMatch[1].toLowerCase()
    ) {
      unsupportedDo = true;
      continue;
    }

    policies.push(`${createStatement};`);
  }

  return { statements: policies, unsupportedDo };
}

/**
 * Compares the Prisma schema models against an existing tenancy-setup.sql file
 * to detect drift: missing tables, extra tables, and incomplete policy definitions.
 */
export function runCheck(options?: CheckOptions): CheckResult {
  const cwd = options?.cwd ?? process.cwd();
  const expectedKey = options?.dbSettingKey ?? DEFAULT_DB_SETTING_KEY;
  const tenantIdField = options?.tenantIdField ?? 'tenant_id';

  if (!isValidPostgresSettingKey(expectedKey)) {
    const warning = 'Invalid database setting key: expected a dotted PostgreSQL custom setting name.';
    console.error(warning);
    return {
      inSync: false,
      missingPolicies: [],
      extraPolicies: [],
      warnings: [warning],
    };
  }

  const schemaPath = findSchemaFile(cwd);
  if (!schemaPath) {
    console.error('No schema.prisma found.');
    return { inSync: false, missingPolicies: [], extraPolicies: [], warnings: [] };
  }

  const sqlPath = path.join(cwd, 'tenancy-setup.sql');
  if (!fs.existsSync(sqlPath)) {
    console.error('No tenancy-setup.sql found. Run `npx @nestarc/tenancy init` first.');
    return { inSync: false, missingPolicies: [], extraPolicies: [], warnings: [] };
  }

  const schemaContent = fs.readFileSync(schemaPath, 'utf-8');
  const sqlContent = fs.readFileSync(sqlPath, 'utf-8');
  const fullSqlScan = scanSql(sqlContent);
  const generatedStartComments = fullSqlScan.lineComments.filter(
    (comment) => comment.text.trim() === GENERATED_START.slice(2).trim(),
  );
  const generatedEndComments = fullSqlScan.lineComments.filter(
    (comment) => comment.text.trim() === GENERATED_END.slice(2).trim(),
  );
  const generatedHeaderComments = fullSqlScan.lineComments.filter(
    (comment) => comment.text.trim() === GENERATED_HEADER,
  );
  const hasCanonicalGeneratedMarkerPair =
    generatedStartComments.length === 1 &&
    generatedEndComments.length === 1 &&
    generatedStartComments[0].start < generatedEndComments[0].start;
  const hasGeneratedMarkerSignal =
    generatedStartComments.length > 0 ||
    generatedEndComments.length > 0 ||
    generatedHeaderComments.length > 0;
  const hasInvalidGeneratedMarkers =
    hasGeneratedMarkerSignal && !hasCanonicalGeneratedMarkerPair;
  const generatedSql = extractGeneratedSqlSection(
    sqlContent,
    fullSqlScan.lineComments,
  );
  const hasGeneratedBoundaries = generatedSql !== sqlContent;
  const generatedSqlScan = generatedSql === sqlContent
    ? fullSqlScan
    : scanSql(generatedSql);
  const generatedTopLevelStatements = generatedSqlScan.statements
    .map((statement) => statement.replace(/;\s*$/, '').trim())
    .filter((statement) => statement.length > 0);
  const hasCanonicalTransactionEnvelope = !hasGeneratedBoundaries || (
    generatedTopLevelStatements[0] === 'BEGIN' &&
    generatedTopLevelStatements.at(-1) === 'COMMIT' &&
    generatedTopLevelStatements.filter((statement) => statement === 'BEGIN')
      .length === 1 &&
    generatedTopLevelStatements.filter((statement) => statement === 'COMMIT')
      .length === 1
  );
  const hasUnguardedTopLevelPolicy = hasGeneratedBoundaries &&
    generatedTopLevelStatements.some((statement) =>
      /^CREATE\s+POLICY(?:\s|$)/i.test(
        maskSqlQuotedIdentifiers(statement),
      ),
    );
  const hasUnsupportedTopLevelStatement = hasGeneratedBoundaries &&
    generatedTopLevelStatements.some(
      (statement) => !isSupportedGeneratedTopLevelStatement(statement),
    );
  const guardedPolicyInspection = inspectGuardedPolicyStatements(
    generatedSqlScan,
  );
  const scannedSql = guardedPolicyInspection.statements.length === 0
    ? generatedSqlScan
    : scanSql(
      `${generatedSql}\n${guardedPolicyInspection.statements.join('\n')}`,
    );
  const sqlForAnalysis = scannedSql.code;
  const statementsForAnalysis = scannedSql.statements
    .map((statement) => statement.replace(/;\s*$/, '').trim())
    .filter((statement) => statement.length > 0);

  const models = parseModels(schemaContent);
  const expectedTableNames = new Map(
    models.map((model) => {
      const displayName = qualifiedName(model);
      return [canonicalTableName(displayName), displayName] as const;
    }),
  );
  const expectedGeneratedNames = new Map(
    models.map((model) => {
      const displayName = qualifiedName(model);
      return [
        canonicalTableName(displayName),
        generateRelationNames({
          schemaName: model.schemaName,
          tableName: model.tableName,
          tenantIdField,
        }),
      ] as const;
    }),
  );
  const expectedTables = new Set(expectedTableNames.keys());
  const allModelTables = new Set(expectedTables);
  const expectedSchemaIdentifiers = new Set([
    quoteSqlIdentifier('public'),
    ...models.map((model) =>
      quoteSqlIdentifier(model.schemaName ?? 'public')
    ),
  ]);

  // Parse tables with RLS enabled from SQL
  const quotedIdentifier = '"(?:[^"]|"")*"';
  const qualifiedTable = `${quotedIdentifier}(?:\\.${quotedIdentifier})?`;
  const appTableGrantRegex = new RegExp(
    `^GRANT\\s+SELECT\\s*,\\s*INSERT\\s*,\\s*UPDATE\\s*,\\s*DELETE\\s+ON\\s+(${qualifiedTable})\\s+TO\\s+app_user$`,
    'i',
  );
  const tableStateRegex = new RegExp(
    `^ALTER\\s+TABLE\\s+(${qualifiedTable})\\s+(?:ENABLE|FORCE)\\s+ROW\\s+LEVEL\\s+SECURITY$`,
    'i',
  );
  const indexTargetRegex = new RegExp(
    `^CREATE\\s+INDEX\\s+IF\\s+NOT\\s+EXISTS\\s+[A-Za-z_][A-Za-z0-9_]*\\s+ON\\s+(${qualifiedTable})\\s+\\(`,
    'i',
  );
  const schemaUsageGrantRegex = new RegExp(
    `^GRANT\\s+USAGE\\s+ON\\s+SCHEMA\\s+(${quotedIdentifier})\\s+TO\\s+app_user$`,
    'i',
  );
  const schemaSequenceGrantRegex = new RegExp(
    `^GRANT\\s+USAGE\\s*,\\s*SELECT\\s+ON\\s+ALL\\s+SEQUENCES\\s+IN\\s+SCHEMA\\s+(${quotedIdentifier})\\s+TO\\s+app_user$`,
    'i',
  );
  const rlsRegex = new RegExp(
    `^ALTER TABLE\\s+(${qualifiedTable})\\s+ENABLE ROW LEVEL SECURITY$`,
  );
  const sqlTables = new Set<string>();
  const sqlTableNames = new Map<string, string>();
  const unqualifiedGeneratedTables = new Set<string>();
  let match: RegExpExecArray | null;
  for (const statement of statementsForAnalysis) {
    match = rlsRegex.exec(statement);
    if (match) {
      const canonicalName = canonicalTableName(match[1]);
      sqlTables.add(canonicalName);
      sqlTableNames.set(canonicalName, match[1]);
      if (hasGeneratedBoundaries && match[1] !== canonicalName) {
        unqualifiedGeneratedTables.add(match[1]);
      }
    }
  }
  if (hasGeneratedBoundaries) {
    for (const statement of statementsForAnalysis) {
      const grantMatch = appTableGrantRegex.exec(statement);
      if (
        grantMatch !== null &&
        grantMatch[1] !== canonicalTableName(grantMatch[1])
      ) {
        unqualifiedGeneratedTables.add(grantMatch[1]);
      }
    }
  }

  // Detect shared models
  const sharedRegex = /-- (\w+) \(shared model\)/g;
  const sharedModelMarkers = new Set<string>();
  const lineCommentSql = scannedSql.lineComments
    .map((comment) => '--' + comment.text)
    .join('\n');
  while ((match = sharedRegex.exec(lineCommentSql)) !== null) {
    sharedModelMarkers.add(match[1]);
  }

  // A generated shared-model marker is authoritative only together with the
  // exact table grant emitted for that model. A lone comment must not hide a
  // missing RLS configuration.
  for (const model of models) {
    if (!sharedModelMarkers.has(model.modelName)) continue;
    const expectedTable = canonicalTableName(qualifiedName(model));
    const hasGeneratedGrant = statementsForAnalysis.some((statement) => {
      const grantMatch = appTableGrantRegex.exec(statement);
      if (
        grantMatch === null ||
        canonicalTableName(grantMatch[1]) !== expectedTable
      ) {
        return false;
      }
      if (hasGeneratedBoundaries && grantMatch[1] !== expectedTable) {
        unqualifiedGeneratedTables.add(grantMatch[1]);
      }
      return true;
    });
    if (hasGeneratedGrant) expectedTables.delete(expectedTable);
  }

  let hasUnexpectedGeneratedTarget = false;
  const schemaUsageTargets = new Set<string>();
  const schemaSequenceTargets = new Set<string>();
  if (hasGeneratedBoundaries) {
    for (const statement of generatedTopLevelStatements) {
      const tableGrantMatch = appTableGrantRegex.exec(statement);
      if (
        tableGrantMatch !== null &&
        !allModelTables.has(canonicalTableName(tableGrantMatch[1]))
      ) {
        hasUnexpectedGeneratedTarget = true;
      }

      const tableStateMatch = tableStateRegex.exec(statement);
      if (
        tableStateMatch !== null &&
        !expectedTables.has(canonicalTableName(tableStateMatch[1]))
      ) {
        hasUnexpectedGeneratedTarget = true;
      }

      const indexTargetMatch = indexTargetRegex.exec(statement);
      if (
        indexTargetMatch !== null &&
        !expectedTables.has(canonicalTableName(indexTargetMatch[1]))
      ) {
        hasUnexpectedGeneratedTarget = true;
      }

      const schemaUsageMatch = schemaUsageGrantRegex.exec(statement);
      if (schemaUsageMatch !== null) {
        schemaUsageTargets.add(schemaUsageMatch[1]);
        if (!expectedSchemaIdentifiers.has(schemaUsageMatch[1])) {
          hasUnexpectedGeneratedTarget = true;
        }
      }

      const schemaSequenceMatch = schemaSequenceGrantRegex.exec(statement);
      if (schemaSequenceMatch !== null) {
        schemaSequenceTargets.add(schemaSequenceMatch[1]);
        if (!expectedSchemaIdentifiers.has(schemaSequenceMatch[1])) {
          hasUnexpectedGeneratedTarget = true;
        }
      }
    }
  }
  const hasMissingGeneratedSchemaGrant = hasGeneratedBoundaries &&
    [...expectedSchemaIdentifiers].some(
      (schema) =>
        !schemaUsageTargets.has(schema) || !schemaSequenceTargets.has(schema),
    );

  const missingPolicies: string[] = [];
  const extraPolicies: string[] = [];
  const warnings: string[] = [];

  if (!scannedSql.valid) {
    warnings.push('Invalid or unsupported SQL lexical structure');
  }
  if (hasInvalidGeneratedMarkers) {
    warnings.push(
      'Generated SQL: missing, duplicate, or out-of-order boundary markers',
    );
  }
  if (guardedPolicyInspection.unsupportedDo) {
    warnings.push('Generated SQL: unsupported or non-canonical DO block');
  }
  if (!hasCanonicalTransactionEnvelope) {
    warnings.push(
      'Generated SQL: missing or non-canonical BEGIN/COMMIT transaction envelope',
    );
  }
  if (hasUnguardedTopLevelPolicy) {
    warnings.push('Generated SQL: unguarded top-level CREATE POLICY');
  }
  if (hasUnsupportedTopLevelStatement) {
    warnings.push('Generated SQL: unsupported top-level statement');
  }
  if (hasUnexpectedGeneratedTarget) {
    warnings.push('Generated SQL: unexpected table or schema target');
  }
  if (hasMissingGeneratedSchemaGrant) {
    warnings.push('Generated SQL: missing required schema grant');
  }
  for (const table of unqualifiedGeneratedTables) {
    warnings.push(
      `${table}: unqualified generated table target; expected explicit "public" schema`,
    );
  }

  for (const canonicalName of expectedTables) {
    if (!sqlTables.has(canonicalName)) {
      missingPolicies.push(expectedTableNames.get(canonicalName) ?? canonicalName);
    }
  }

  for (const canonicalName of sqlTables) {
    if (!expectedTables.has(canonicalName)) {
      extraPolicies.push(sqlTableNames.get(canonicalName) ?? canonicalName);
    }
  }

  const expectedKeyTokens = scannedSql.stringLiterals
    .map((literal, index) => ({ literal, index }))
    .filter(({ literal }) => literal.standard && literal.value === expectedKey)
    .map(({ index }) => escapeRegExp(sqlStringToken(index)));
  const expectedKeyPattern = expectedKeyTokens.length > 0
    ? '(?:' + expectedKeyTokens.join('|') + ')'
    : '(?!)';
  const recognizedPolicyStatements = new Set<string>();

  // Deep checks: FORCE, policies, setting key
  for (const canonicalName of sqlTables) {
    if (!expectedTables.has(canonicalName)) continue;
    const table = sqlTableNames.get(canonicalName) ?? canonicalName;

    // Check FORCE ROW LEVEL SECURITY
    const forceRegex = new RegExp(
      `^ALTER TABLE ${escapeRegExp(table)} FORCE ROW LEVEL SECURITY$`,
    );
    if (!statementsForAnalysis.some((statement) => forceRegex.test(statement))) {
      warnings.push(`${table}: missing FORCE ROW LEVEL SECURITY`);
    }

    // Check isolation policy (SELECT/UPDATE/DELETE)
    const escapedTable = table.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    if (
      hasGeneratedBoundaries &&
      !statementsForAnalysis.some((statement) => {
        const grantMatch = appTableGrantRegex.exec(statement);
        return grantMatch !== null && grantMatch[1] === table;
      })
    ) {
      warnings.push(`${table}: missing or invalid application table grant`);
    }
    const escapedQuotedTenantField = escapeRegExp(
      quoteSqlIdentifier(tenantIdField),
    );
    const escapedTenantField = escapeRegExp(tenantIdField);
    const unquotedTenantFieldAlternative =
      /^[a-z_][a-z0-9_$]*$/.test(tenantIdField)
        ? `|\\b${escapedTenantField}\\b`
        : '';
    const tenantColumnPattern =
      `(?:${escapedQuotedTenantField}${unquotedTenantFieldAlternative})`;
    const tenantPredicate =
      `${tenantColumnPattern}\\s*=\\s*current_setting\\s*\\(\\s*${expectedKeyPattern}\\s*,\\s*true\\s*\\)\\s*::\\s*text`;
    const policyStatements = statementsForAnalysis;
    const expectedNames = expectedGeneratedNames.get(canonicalName);
    const isolationNamePattern = hasGeneratedBoundaries && expectedNames
      ? escapeRegExp(expectedNames.isolationPolicy)
      : 'tenant_isolation_\\S+';
    const isolationRegex = new RegExp(
      `^CREATE POLICY\\s+${isolationNamePattern}\\s+ON\\s+${escapedTable}\\s+USING\\s*\\(\\s*${tenantPredicate}\\s*\\)$`,
    );
    const matchingIsolationPolicies = policyStatements.filter((statement) =>
      isolationRegex.test(statement),
    );
    for (const statement of matchingIsolationPolicies) {
      recognizedPolicyStatements.add(statement);
    }
    if (matchingIsolationPolicies.length !== 1) {
      warnings.push(`${table}: missing or invalid tenant_isolation policy`);
    }

    // Check insert policy
    const insertNamePattern = hasGeneratedBoundaries && expectedNames
      ? escapeRegExp(expectedNames.insertPolicy)
      : 'tenant_insert_\\S+';
    const insertRegex = new RegExp(
      `^CREATE POLICY\\s+${insertNamePattern}\\s+ON\\s+${escapedTable}\\s+FOR\\s+INSERT\\s+WITH\\s+CHECK\\s*\\(\\s*${tenantPredicate}\\s*\\)$`,
    );
    const matchingInsertPolicies = policyStatements.filter((statement) =>
      insertRegex.test(statement),
    );
    for (const statement of matchingInsertPolicies) {
      recognizedPolicyStatements.add(statement);
    }
    if (matchingInsertPolicies.length !== 1) {
      warnings.push(`${table}: missing or invalid tenant_insert policy`);
    }

    const policyName = '(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$]*)';
    const tablePolicyRegex = new RegExp(
      `^CREATE\\s+POLICY\\s+${policyName}\\s+ON\\s+${escapedTable}(?:\\s|$)`,
      'i',
    );
    const restrictivePolicyRegex = new RegExp(
      `^CREATE\\s+POLICY\\s+${policyName}\\s+ON\\s+${escapedTable}\\s+AS\\s+RESTRICTIVE(?:\\s|$)`,
      'i',
    );
    const tablePolicyStatements = policyStatements.filter((statement) =>
      tablePolicyRegex.test(statement),
    );
    const unexpectedPermissivePolicies = tablePolicyStatements.filter(
      (statement) => !recognizedPolicyStatements.has(statement) &&
        !restrictivePolicyRegex.test(statement),
    );
    for (const statement of tablePolicyStatements) {
      if (restrictivePolicyRegex.test(statement)) {
        recognizedPolicyStatements.add(statement);
      }
    }
    if (unexpectedPermissivePolicies.length > 0) {
      warnings.push(`${table}: unexpected permissive policy`);
    }

    // Check tenant column index. RLS policies are implicit filters, so tenant
    // scoped tables should index the policy column to avoid full table scans.
    const indexNamePattern = hasGeneratedBoundaries && expectedNames
      ? escapeRegExp(expectedNames.index)
      : '\\S+';
    const tenantIndexRegex = new RegExp(
      `^CREATE\\s+(?:UNIQUE\\s+)?INDEX(?:\\s+IF\\s+NOT\\s+EXISTS)?\\s+${indexNamePattern}\\s+ON\\s+${escapedTable}\\s+(?:USING\\s+\\w+\\s+)?\\([^)]*${tenantColumnPattern}[^)]*\\)$`,
    );
    if (!statementsForAnalysis.some((statement) => tenantIndexRegex.test(statement))) {
      warnings.push(`${table}: missing tenant index on ${tenantIdField}`);
    }
  }

  const statementsWithMaskedIdentifiers = statementsForAnalysis.map(
    (statement) => ({
      statement,
      keywords: maskSqlQuotedIdentifiers(statement),
    }),
  );
  const hasUnrecognizedPolicy = statementsWithMaskedIdentifiers.some(
    ({ statement, keywords }) =>
      /^CREATE\s+POLICY(?:\s|$)/i.test(keywords) &&
      !recognizedPolicyStatements.has(statement),
  );
  if (hasUnrecognizedPolicy) {
    warnings.push('Generated SQL: unexpected permissive or unsupported policy');
  }

  // Any policy mutation or RLS reversal in the generated section is invalid,
  // regardless of how PostgreSQL-equivalent identifiers are spelled.
  const hasStateReversingStatement = statementsWithMaskedIdentifiers.some(
    ({ keywords }) =>
      /^(?:ALTER|DROP)\s+POLICY(?:\s|$)/i.test(keywords) ||
      /^ALTER\s+TABLE(?:\s|$)[\s\S]*?(?:\s+|,\s*)(?:DISABLE\s+ROW\s+LEVEL\s+SECURITY|NO\s+FORCE\s+ROW\s+LEVEL\s+SECURITY)(?=\s*(?:,|$))/i
        .test(keywords),
  );
  if (hasStateReversingStatement) {
    warnings.push('Generated SQL: unexpected policy or RLS mutation');
  }

  // Check setting key consistency across ALL current_setting() calls
  const functionCode = maskSqlQuotedIdentifiers(sqlForAnalysis);
  const keyRegex =
    /(^|[^A-Za-z0-9_$\u0080-\uFFFF])current_setting\s*\(\s*([^,)]*)/giu;
  for (const keyMatch of functionCode.matchAll(keyRegex)) {
    const literalIndex = sqlStringTokenIndex(keyMatch[2].trim());
    const literal = literalIndex === undefined
      ? undefined
      : scannedSql.stringLiterals[literalIndex];
    if (!literal?.standard || literal.value !== expectedKey) {
      warnings.push(
        `Setting key mismatch or unsupported current_setting() argument; expected '${expectedKey}'`,
      );
    }
  }

  const inSync =
    missingPolicies.length === 0 &&
    extraPolicies.length === 0 &&
    warnings.length === 0;

  if (inSync) {
    console.log('OK — tenancy-setup.sql is in sync with Prisma schema.');
  } else {
    if (missingPolicies.length > 0) {
      console.log(`Missing RLS policies for: ${missingPolicies.join(', ')}`);
    }
    if (extraPolicies.length > 0) {
      console.log(`Extra RLS policies (not in schema): ${extraPolicies.join(', ')}`);
    }
    for (const w of warnings) {
      console.log(`Warning: ${w}`);
    }
    console.log('\nRe-run `npx @nestarc/tenancy init` to regenerate.');
  }

  return { inSync, missingPolicies, extraPolicies, warnings };
}

function findSchemaFile(cwd: string): string | null {
  const candidates = [
    path.join(cwd, 'schema.prisma'),
    path.join(cwd, 'prisma', 'schema.prisma'),
  ];
  return candidates.find((p) => fs.existsSync(p)) ?? null;
}
