import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as ts from 'typescript';
import { parseModels } from '../../src/cli/prisma-schema-parser';
import { generateSetupSql } from '../../src/cli/templates/setup-sql';
import { generateModuleSetup } from '../../src/cli/templates/module-setup';

function formatDiagnostic(diagnostic: ts.Diagnostic): string {
  return ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
}

function generatedIdentifiers(sql: string): string[] {
  return [...sql.matchAll(
    /\bCREATE (?:INDEX IF NOT EXISTS|POLICY) ([A-Za-z_][A-Za-z0-9_]*)/g,
  )].map((match) => match[1]);
}

describe('generateSetupSql', () => {
  const baseOptions = {
    models: [],
    dbSettingKey: 'app.current_tenant',
    sharedModels: [],
    tenantIdField: 'tenant_id',
  };

  it('should include standard header and role creation', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain('-- Generated by @nestarc/tenancy CLI');
    expect(sql).toContain('CREATE ROLE app_user');
    expect(sql).toContain('GRANT USAGE ON SCHEMA "public" TO app_user;');
  });

  it('should not generate a hardcoded app_user password', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).not.toContain("'changeme'");
    expect(sql).toContain('ALTER ROLE app_user WITH PASSWORD');
  });

  it('should wrap generated SQL with boundary markers', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain('-- BEGIN GENERATED TENANCY SQL');
    expect(sql).toContain('-- END GENERATED TENANCY SQL');
  });

  it('should make the generated block an explicit transaction', () => {
    const sql = generateSetupSql(baseOptions);
    const beginMarker = sql.indexOf('-- BEGIN GENERATED TENANCY SQL');
    const begin = sql.indexOf('BEGIN;');
    const commit = sql.indexOf('COMMIT;');
    const endMarker = sql.indexOf('-- END GENERATED TENANCY SQL');

    expect(beginMarker).toBeGreaterThanOrEqual(0);
    expect(begin).toBeGreaterThan(beginMarker);
    expect(commit).toBeGreaterThan(begin);
    expect(endMarker).toBeGreaterThan(commit);
    expect(sql.match(/^BEGIN;$/gm)).toHaveLength(1);
    expect(sql.match(/^COMMIT;$/gm)).toHaveLength(1);
    expect(sql).toContain('-X -v ON_ERROR_STOP=1');
    expect(sql).toContain('not ON_ERROR_ROLLBACK=on');
  });

  it('should include tenant_id warning comment in header', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain("-- IMPORTANT: This script assumes all non-shared models have a 'tenant_id' column.");
    expect(sql).toContain("-- Remove or modify policies for models that don't use tenant isolation.");
  });

  it('should include general sequence grant at the end', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "public" TO app_user;');
  });

  it('should generate RLS policies for non-shared models', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'User', tableName: 'User' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "public"."User" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('ALTER TABLE "public"."User" FORCE ROW LEVEL SECURITY;');
    expect(sql).toContain(
      'CREATE POLICY tenant_isolation_User_940d88379add ON "public"."User"',
    );
    expect(sql).toContain("current_setting('app.current_tenant', true)::text");
    expect(sql).toContain(
      'CREATE POLICY tenant_insert_User_b8b33f29d481 ON "public"."User"',
    );
    expect(sql).toContain(
      'CREATE POLICY tenant_context_guard_User_ece5e1ee8731 ON "public"."User"',
    );
    expect(sql).toContain(
      'CREATE INDEX IF NOT EXISTS tenancy_User_tenant_id_idx_44e3041c39d1 ON "public"."User" ("tenant_id");',
    );
    expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."User" TO app_user;');
  });

  it('should preserve the exact TEXT tenant predicate for parser-origin models', () => {
    const sql = generateSetupSql({
      ...baseOptions,
      models: parseModels(`model Account {
  id       Int    @id
  tenantId String @map("tenant_id")
}`),
    });
    const textPredicate =
      `"tenant_id" = current_setting('app.current_tenant', true)::text`;

    expect(sql.split(textPredicate)).toHaveLength(3);
    expect(sql).not.toContain(`"tenant_id" = NULLIF(current_setting`);
  });

  it('should generate the UUID predicate with an empty-setting guard', () => {
    const sql = generateSetupSql({
      ...baseOptions,
      models: parseModels(`model Account {
  id       Int    @id
  tenantId String @db.Uuid @map("tenant_id")
}`),
    });
    const uuidPredicate =
      `"tenant_id" = NULLIF(current_setting('app.current_tenant', true), '')::uuid`;

    expect(sql.split(uuidPredicate)).toHaveLength(3);
    expect(sql).not.toContain(
      `"tenant_id" = current_setting('app.current_tenant', true)::text`,
    );
  });

  it('should add an idempotent restrictive context guard for reads and writes', () => {
    const sql = generateSetupSql({
      ...baseOptions,
      models: [{ modelName: 'Account', tableName: 'accounts' }],
    });
    const guardPredicate =
      `NULLIF(current_setting('app.current_tenant', true), '') IS NOT NULL`;

    expect(sql).toContain(
      'CREATE POLICY tenant_context_guard_accounts ON "public"."accounts"',
    );
    expect(sql).toContain(
      "p.polname = 'tenant_context_guard_accounts'::pg_catalog.name",
    );
    expect(sql).toContain('  AS RESTRICTIVE');
    expect(sql).toContain(`  USING (${guardPredicate})`);
    expect(sql).toContain(`  WITH CHECK (${guardPredicate});`);
    expect(sql.split(guardPredicate)).toHaveLength(3);
  });

  it('should preserve existing generated policies for drift review on reapply', () => {
    const sql = generateSetupSql({
      ...baseOptions,
      models: [{ modelName: 'User', tableName: 'User' }],
    });

    expect(sql).toContain('FROM pg_catalog.pg_policy AS p');
    expect(sql).toContain(
      'n.nspname = $tenancy_identifier$public$tenancy_identifier$',
    );
    expect(sql).toContain(
      'c.relname = $tenancy_identifier$User$tenancy_identifier$',
    );
    expect(sql).toContain(
      "p.polname = 'tenant_isolation_user_940d88379add'::pg_catalog.name",
    );
    expect(sql).toContain(
      "p.polname = 'tenant_insert_user_b8b33f29d481'::pg_catalog.name",
    );
    expect(sql).toContain(
      "p.polname = 'tenant_context_guard_user_ece5e1ee8731'::pg_catalog.name",
    );
    expect(sql).not.toMatch(/^DROP POLICY/m);
    expect(sql).toMatch(/existing policies.+preserved/i);
    expect(sql).toMatch(/atomic replacement.+explicit.+DROP POLICY/i);
  });

  it('should choose a dollar-quote tag absent from mapped identifiers', () => {
    const sql = generateSetupSql({
      ...baseOptions,
      models: [{
        modelName: 'LedgerEntry',
        tableName: 'ledger$tenancy_policy$archive',
      }],
    });

    expect(sql).toContain('DO $tenancy_policy_1$');
    expect(sql).toContain('ON "public"."ledger$tenancy_policy$archive"');
  });

  it('should choose a guard literal tag absent from mapped identifiers', () => {
    const sql = generateSetupSql({
      ...baseOptions,
      models: [{
        modelName: 'LedgerEntry',
        schemaName: 'ops$tenancy_identifier$archive',
        tableName: 'ledger',
      }],
    });

    expect(sql).toContain(
      'n.nspname = $tenancy_identifier_1$ops$tenancy_identifier$archive$tenancy_identifier_1$',
    );
  });

  it('should use custom dbSettingKey in policies', () => {
    const options = {
      ...baseOptions,
      dbSettingKey: 'app.tenant',
      models: [{ modelName: 'Post', tableName: 'posts' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain("current_setting('app.tenant', true)::text");
  });

  it.each([
    'current_tenant',
    'app.',
    'app.tenant-key',
    'app.tenant\nkey',
    'app.tenant\0key',
  ])('should reject an invalid database setting key: %p', (dbSettingKey) => {
    expect(() => generateSetupSql({
      ...baseOptions,
      dbSettingKey,
      models: [{ modelName: 'Post', tableName: 'posts' }],
    })).toThrow(/database setting key/i);
  });

  it('should quote mapped schema, table, and tenant column identifiers independently', () => {
    const sql = generateSetupSql({
      ...baseOptions,
      models: [{
        modelName: 'LedgerEntry',
        schemaName: 'tenant"ops',
        tableName: 'ledger;\narchive',
      }],
      tenantIdField: 'tenant"id',
    });

    expect(sql).toContain('ALTER TABLE "tenant""ops"."ledger;\narchive" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('("tenant""id")');
    expect(sql).toContain('USING ("tenant""id" = current_setting(\'app.current_tenant\', true)::text);');
  });

  it.each([
    ['NUL table', { modelName: 'Order', tableName: 'orders\0archive' }],
    ['long table', { modelName: 'Order', tableName: 'o'.repeat(64) }],
    ['NUL schema', { modelName: 'Order', tableName: 'orders', schemaName: 'ops\0archive' }],
    ['long schema', { modelName: 'Order', tableName: 'orders', schemaName: 's'.repeat(64) }],
  ])('should reject an invalid PostgreSQL identifier: %s', (_label, model) => {
    expect(() => generateSetupSql({
      ...baseOptions,
      models: [model],
    })).toThrow(/PostgreSQL identifier/i);
  });

  it('should reject a model name containing NUL', () => {
    expect(() => generateSetupSql({
      ...baseOptions,
      models: [{ modelName: 'Order\0Archive', tableName: 'orders' }],
    })).toThrow(/Prisma model name/i);
  });

  it('should use mapped tableName in policies', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'User', tableName: 'users' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('ALTER TABLE "public"."users" FORCE ROW LEVEL SECURITY;');
    expect(sql).toContain('CREATE POLICY tenant_isolation_users ON "public"."users"');
    expect(sql).not.toContain('"User"');
  });

  it('should generate GRANT without RLS for shared models', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'Country', tableName: 'Country' }],
      sharedModels: ['Country'],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('-- Country (shared model)');
    expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."Country" TO app_user;');
    expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
    expect(sql).not.toContain('CREATE INDEX IF NOT EXISTS tenancy_Country_tenant_id_idx');
  });

  it('should handle a mix of shared and non-shared models', () => {
    const options = {
      ...baseOptions,
      models: [
        { modelName: 'User', tableName: 'User' },
        { modelName: 'Country', tableName: 'Country' },
      ],
      sharedModels: ['Country'],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "public"."User" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('-- Country (shared model)');
    expect(sql).not.toContain('ALTER TABLE "Country" ENABLE ROW LEVEL SECURITY');
  });

  it('should produce valid output for empty models list', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toBeTruthy();
    expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
    expect(sql).not.toContain('(shared model)');
  });

  it('should use custom tenantIdField in policy', () => {
    const options = {
      ...baseOptions,
      tenantIdField: 'org_id',
      models: [{ modelName: 'Order', tableName: 'orders' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('"org_id" = current_setting');
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS tenancy_orders_org_id_idx ON "public"."orders" ("org_id");');
  });

  it('should sanitize hyphenated table names in policy identifiers', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'AuditLog', tableName: 'audit-logs' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "public"."audit-logs" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('ALTER TABLE "public"."audit-logs" FORCE ROW LEVEL SECURITY;');
    expect(sql).toContain(
      'CREATE POLICY tenant_isolation_audit_logs_ae80b988a44e ON "public"."audit-logs"',
    );
    expect(sql).toContain(
      'CREATE POLICY tenant_insert_audit_logs_4aa2515f122e ON "public"."audit-logs"',
    );
    expect(sql).toContain(
      'CREATE POLICY tenant_context_guard_audit_logs_0773d7065a99 ON "public"."audit-logs"',
    );
    expect(sql).not.toContain('tenant_isolation_audit-logs');
    expect(sql).not.toContain('tenant_insert_audit-logs');
    expect(sql).not.toContain('tenant_context_guard_audit-logs');
  });

  it('should deterministically disambiguate generated identifiers after normalization', () => {
    const options = {
      ...baseOptions,
      models: [
        { modelName: 'DashedAuditLog', tableName: 'audit-logs' },
        { modelName: 'UnderscoredAuditLog', tableName: 'audit_logs' },
      ],
    };

    const identifiers = generatedIdentifiers(generateSetupSql(options));
    expect(identifiers).toHaveLength(8);
    expect(new Set(identifiers).size).toBe(8);
    expect(identifiers).toEqual(
      generatedIdentifiers(generateSetupSql(options)),
    );
    expect(identifiers).toEqual([
      'tenancy_audit_logs_tenant_id_idx_07148afa054f',
      'tenant_isolation_audit_logs_ae80b988a44e',
      'tenant_insert_audit_logs_4aa2515f122e',
      'tenant_context_guard_audit_logs_0773d7065a99',
      'tenancy_audit_logs_tenant_id_idx',
      'tenant_isolation_audit_logs',
      'tenant_insert_audit_logs',
      'tenant_context_guard_audit_logs',
    ]);
    expect(generatedIdentifiers(generateSetupSql({
      ...options,
      models: [...options.models].reverse(),
    })).sort()).toEqual([...identifiers].sort());
    expect(identifiers.slice(4)).toEqual(generatedIdentifiers(
      generateSetupSql({
        ...options,
        models: [options.models[1]],
      }),
    ));
  });

  it('should keep long generated identifiers unique and within 63 UTF-8 bytes', () => {
    const commonPrefix = 'a'.repeat(58);
    const options = {
      ...baseOptions,
      models: [
        { modelName: 'LongAccountA', tableName: `${commonPrefix}a` },
        { modelName: 'LongAccountB', tableName: `${commonPrefix}b` },
      ],
    };

    const identifiers = generatedIdentifiers(generateSetupSql(options));
    expect(identifiers).toHaveLength(8);
    expect(new Set(identifiers).size).toBe(8);
    expect(identifiers.every(
      (identifier) => Buffer.byteLength(identifier, 'utf8') <= 63,
    )).toBe(true);
    expect(identifiers[0]).toBe(
      'tenancy_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_7e7d6f293149',
    );
  });

  it('should disambiguate names that PostgreSQL folds to the same case', () => {
    const identifiers = generatedIdentifiers(generateSetupSql({
      ...baseOptions,
      models: [
        { modelName: 'UpperUser', tableName: 'User' },
        { modelName: 'LowerUser', tableName: 'user' },
      ],
    }));

    expect(identifiers).toHaveLength(8);
    expect(new Set(identifiers.map((identifier) => identifier.toLowerCase())).size)
      .toBe(8);
    expect(identifiers.slice(0, 4).every(
      (identifier) => /_[0-9a-f]{12}$/.test(identifier),
    )).toBe(true);
    expect(identifiers.slice(4)).toEqual([
      'tenancy_user_tenant_id_idx',
      'tenant_isolation_user',
      'tenant_insert_user',
      'tenant_context_guard_user',
    ]);
  });

  it('should derive the index name from the raw tenant column identity', () => {
    const lossyNames = generatedIdentifiers(generateSetupSql({
      ...baseOptions,
      models: [{ modelName: 'Account', tableName: 'accounts' }],
      tenantIdField: 'tenant-id',
    }));
    const canonicalNames = generatedIdentifiers(generateSetupSql({
      ...baseOptions,
      models: [{ modelName: 'Account', tableName: 'accounts' }],
      tenantIdField: 'tenant_id',
    }));

    expect(lossyNames[0]).toMatch(
      /^tenancy_accounts_tenant_id_idx_[0-9a-f]{12}$/,
    );
    expect(lossyNames[0]).not.toBe(canonicalNames[0]);
    expect(lossyNames.slice(1)).toEqual(canonicalNames.slice(1));
  });

  it('should disambiguate Unicode identifiers that normalize to underscores', () => {
    const identifiers = generatedIdentifiers(generateSetupSql({
      ...baseOptions,
      models: [
        { modelName: 'KoreanA', tableName: '가' },
        { modelName: 'KoreanB', tableName: '나' },
      ],
    }));

    expect(identifiers).toHaveLength(8);
    expect(new Set(identifiers.map((identifier) => identifier.toLowerCase())).size)
      .toBe(8);
    expect(identifiers.every((identifier) => /_[0-9a-f]{12}$/.test(identifier)))
      .toBe(true);
  });

  it('should canonicalize explicit and implicit public schema names identically', () => {
    const implicit = generatedIdentifiers(generateSetupSql({
      ...baseOptions,
      models: [{ modelName: 'Account', tableName: 'accounts' }],
    }));
    const explicit = generatedIdentifiers(generateSetupSql({
      ...baseOptions,
      models: [{
        modelName: 'Account',
        schemaName: 'public',
        tableName: 'accounts',
      }],
    }));

    expect(explicit).toEqual(implicit);
  });

  describe('@@schema support', () => {
    it('should generate schema-qualified table names', () => {
      const options = {
        ...baseOptions,
        models: [{ modelName: 'User', tableName: 'users', schemaName: 'auth' }],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('ALTER TABLE "auth"."users" ENABLE ROW LEVEL SECURITY;');
      expect(sql).toContain('ALTER TABLE "auth"."users" FORCE ROW LEVEL SECURITY;');
      expect(sql).toContain('CREATE POLICY tenant_isolation_auth_users ON "auth"."users"');
      expect(sql).toContain('CREATE POLICY tenant_insert_auth_users ON "auth"."users"');
      expect(sql).toContain('CREATE POLICY tenant_context_guard_auth_users ON "auth"."users"');
      expect(sql).toContain('CREATE INDEX IF NOT EXISTS tenancy_auth_users_tenant_id_idx ON "auth"."users" ("tenant_id");');
      expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "auth"."users" TO app_user;');
    });

    it('should include GRANT USAGE for non-public schemas', () => {
      const options = {
        ...baseOptions,
        models: [{ modelName: 'User', tableName: 'users', schemaName: 'auth' }],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('GRANT USAGE ON SCHEMA "auth" TO app_user;');
      expect(sql).toContain('GRANT USAGE ON SCHEMA "public" TO app_user;');
    });

    it('should include sequence grants for each schema', () => {
      const options = {
        ...baseOptions,
        models: [
          { modelName: 'User', tableName: 'users', schemaName: 'auth' },
          { modelName: 'Order', tableName: 'orders' },
        ],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "auth" TO app_user;');
      expect(sql).toContain('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "public" TO app_user;');
    });

    it('should handle mix of schema and non-schema models', () => {
      const options = {
        ...baseOptions,
        models: [
          { modelName: 'User', tableName: 'users', schemaName: 'auth' },
          { modelName: 'Post', tableName: 'posts' },
        ],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('ALTER TABLE "auth"."users" ENABLE ROW LEVEL SECURITY;');
      expect(sql).toContain('ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;');
      expect(sql).not.toContain('"auth"."posts"');
    });

    it('should include schema prefix in policy names to avoid collisions', () => {
      const options = {
        ...baseOptions,
        models: [
          { modelName: 'User', tableName: 'users', schemaName: 'auth' },
          { modelName: 'AdminUser', tableName: 'users', schemaName: 'admin' },
        ],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('tenant_isolation_auth_users');
      expect(sql).toContain('tenant_isolation_admin_users');
    });

    it('should handle shared models with schema', () => {
      const options = {
        ...baseOptions,
        models: [{ modelName: 'Country', tableName: 'countries', schemaName: 'reference' }],
        sharedModels: ['Country'],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('-- Country (shared model)');
      expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "reference"."countries" TO app_user;');
      expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
      expect(sql).not.toContain('tenant_context_guard');
    });
  });
});

describe('generateModuleSetup', () => {
  const baseOptions = {
    extractorType: 'Header (X-Tenant-Id)',
    dbSettingKey: 'app.current_tenant',
    autoInjectTenantId: false,
    sharedModels: [],
  };

  it('should include standard header comment', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain('// Generated by @nestarc/tenancy CLI');
    expect(result).toContain('TenancyModule.forRoot({');
  });

  it('should use Header extractor (default) when type is Header (X-Tenant-Id)', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain("tenantExtractor: 'X-Tenant-Id',");
    expect(result).toContain("import { TenancyModule } from '@nestarc/tenancy';");
    expect(result).toContain("// import { createPrismaTenancyExtension } from '@nestarc/tenancy';");
  });

  it('should use SubdomainTenantExtractor for Subdomain type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Subdomain (tenant1.app.com)',
    });
    expect(result).toContain('new SubdomainTenantExtractor()');
    expect(result).toContain('SubdomainTenantExtractor');
    expect(result).toContain('SubdomainTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should use JwtClaimTenantExtractor for JWT Claim type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'JWT Claim',
    });
    expect(result).toContain("new JwtClaimTenantExtractor({ claimKey: 'tenant_id' })");
    expect(result).toContain('JwtClaimTenantExtractor');
    expect(result).toContain('JwtClaimTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should use PathTenantExtractor for Path Parameter type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Path Parameter',
    });
    expect(result).toContain("new PathTenantExtractor({ pattern: '/api/tenants/:tenantId', paramName: 'tenantId' })");
    expect(result).toContain('PathTenantExtractor');
    expect(result).toContain('PathTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should use Composite scaffold for Composite type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Composite',
    });
    expect(result).toContain('new CompositeTenantExtractor([');
    expect(result).toContain("new HeaderTenantExtractor('X-Tenant-Id'),");
    expect(result).toContain('// Add more extractors here');
    expect(result).toContain('CompositeTenantExtractor');
    expect(result).toContain('HeaderTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should fall through to default (header string) for unknown extractor type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Unknown',
    });
    expect(result).toContain("tenantExtractor: 'X-Tenant-Id',");
  });

  it('should NOT include dbSettingKey when it equals the default app.current_tenant', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).not.toContain('dbSettingKey:');
  });

  it('should include dbSettingKey when it differs from the default', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      dbSettingKey: 'app.tenant',
    });
    expect(result).toContain('dbSettingKey: "app.tenant",');
  });

  it('should keep a custom dbSettingKey only in the canonical module config', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      dbSettingKey: 'app.tenant',
    });
    expect(result).toContain('createPrismaTenancyExtension(tenancyService)');
    expect(result.match(/dbSettingKey: "app\.tenant",/g)).toHaveLength(1);
  });

  it('should not duplicate a custom dbSettingKey into other extension options', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      dbSettingKey: 'app.tenant',
      autoInjectTenantId: true,
    });
    expect(result).toContain('createPrismaTenancyExtension(tenancyService, {');
    expect(result).toContain('autoInjectTenantId: true,');
    expect(result.match(/dbSettingKey: "app\.tenant",/g)).toHaveLength(1);
  });

  it('should always include Prisma extension block', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain('createPrismaTenancyExtension(tenancyService)');
    expect(result).toContain('// Prisma extension — required for RLS to work:');
    expect(result).toContain('// Prisma 7: create basePrisma with the adapter required by your database.');
    expect(result).toContain('// const prisma = basePrisma.$extends(');
    expect(result).not.toContain('new PrismaClient().$extends');
  });

  it('should include options in extension block when autoInjectTenantId is true', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      autoInjectTenantId: true,
    });
    expect(result).toContain('createPrismaTenancyExtension(tenancyService, {');
    expect(result).toContain('autoInjectTenantId: true,');
  });

  it('should emit the mapped logical tenantIdField for auto-injection', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      autoInjectTenantId: true,
      tenantIdField: 'tenantId',
    });

    expect(result).toContain('//     autoInjectTenantId: true,');
    expect(result).toContain('//     tenantIdField: "tenantId",');
  });

  it('should include sharedModels in extension block when provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      sharedModels: ['Country', 'Currency'],
    });
    expect(result).toContain('sharedModels: ["Country","Currency"],');
  });

  it('should serialize generated TypeScript strings and arrays as JSON literals', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      dbSettingKey: 'custom.tenant',
      sharedModels: ['Ledger"Entry', 'Line\nItem', 'Path\\Value'],
    });

    expect(result).toContain(`dbSettingKey: ${JSON.stringify('custom.tenant')},`);
    expect(result).toContain(`sharedModels: ${JSON.stringify(['Ledger"Entry', 'Line\nItem', 'Path\\Value'])},`);
  });

  it('should keep JavaScript line separators escaped inside comments', () => {
    const lineSeparator = String.fromCodePoint(0x2028);
    const paragraphSeparator = String.fromCodePoint(0x2029);
    const result = generateModuleSetup({
      ...baseOptions,
      sharedModels: [
        `Line${lineSeparator}Item`,
        `Paragraph${paragraphSeparator}Item`,
      ],
    });
    const sourceFile = ts.createSourceFile(
      'tenancy.module-setup.ts',
      result,
      ts.ScriptTarget.ES2021,
      true,
      ts.ScriptKind.TS,
    );

    expect(result).toContain('\\u2028');
    expect(result).toContain('\\u2029');
    expect(result).not.toContain(lineSeparator);
    expect(result).not.toContain(paragraphSeparator);
    const parseDiagnostics = (
      sourceFile as ts.SourceFile & { parseDiagnostics: readonly ts.Diagnostic[] }
    ).parseDiagnostics;
    expect(parseDiagnostics).toHaveLength(0);
    expect(sourceFile.statements.filter(ts.isExpressionStatement)).toHaveLength(1);
  });

  it.each([
    'current_tenant',
    'app.tenant-key',
    'app.tenant\nkey',
    'app.tenant\0key',
  ])('should reject an invalid module database setting key: %p', (dbSettingKey) => {
    expect(() => generateModuleSetup({
      ...baseOptions,
      dbSettingKey,
    })).toThrow(/database setting key/i);
  });

  it('should include both autoInjectTenantId and sharedModels when both are provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      autoInjectTenantId: true,
      sharedModels: ['Country'],
    });
    expect(result).toContain('autoInjectTenantId: true,');
    expect(result).toContain('sharedModels: ["Country"],');
  });

  it('should include validateTenantId when tenantFormat is Custom and customRegex is provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '^[a-z0-9-]+$',
    });
    expect(result).toContain('validateTenantId: (id) => new RegExp("^[a-z0-9-]+$").test(id),');
  });

  it('should safely handle customRegex containing forward slashes', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '^acme/.+$',
    });
    expect(result).toContain('validateTenantId: (id) => new RegExp("^acme/.+$").test(id),');
  });

  it('should escape backslashes in customRegex for string context', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '^\\d{3}-\\d{4}$',
    });
    expect(result).toContain('validateTenantId: (id) => new RegExp("^\\\\d{3}-\\\\d{4}$").test(id),');
  });

  it('should safely serialize customRegex containing newlines', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '^abc\ndef$',
    });
    expect(result).toContain('validateTenantId: (id) => new RegExp("^abc\\ndef$").test(id),');
    expect(result).not.toContain("new RegExp('^abc\ndef$')");
  });

  it('should NOT include validateTenantId when tenantFormat is UUID', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'UUID',
      customRegex: '^[a-z0-9-]+$',
    });
    expect(result).not.toContain('validateTenantId');
  });

  it('should NOT include validateTenantId when tenantFormat is Custom but customRegex is empty', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '',
    });
    expect(result).not.toContain('validateTenantId');
  });

  it('should generate TypeScript that passes semantic typechecking', () => {
    const source = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Composite',
      dbSettingKey: 'custom.tenant',
      autoInjectTenantId: true,
      sharedModels: ['Ledger"Entry', 'Line\nItem', 'Path\\Value'],
      tenantFormat: 'Custom',
      customRegex: '^tenant["\\n].+$',
    });
    const tempDir = fs.mkdtempSync(
      path.join(os.tmpdir(), 'tenancy-generated-module-'),
    );
    const generatedPath = path.join(tempDir, 'tenancy.module-setup.ts');
    fs.writeFileSync(generatedPath, source, 'utf-8');

    try {
      const repositoryRoot = path.resolve(__dirname, '../..');
      const program = ts.createProgram({
        rootNames: [
          generatedPath,
          path.join(repositoryRoot, 'src/types/psl.d.ts'),
        ],
        options: {
          module: ts.ModuleKind.Node16,
          moduleResolution: ts.ModuleResolutionKind.Node16,
          target: ts.ScriptTarget.ES2021,
          strict: true,
          noEmit: true,
          skipLibCheck: true,
          esModuleInterop: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          baseUrl: repositoryRoot,
          typeRoots: [path.join(repositoryRoot, 'node_modules/@types')],
          types: ['node'],
          paths: {
            '@nestarc/tenancy': ['src/index.ts'],
          },
          noUnusedLocals: true,
        },
      });
      const diagnostics = ts.getPreEmitDiagnostics(program);

      expect(diagnostics.map(formatDiagnostic)).toEqual([]);
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });
});
